[package]
name = "shopping_rust_shopping"
version = "0.0.1"
edition = "2024"

[workspace]
exclude = ["benchmark"]

[profile.release]
opt-level = "s"
lto = true

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
log = { version = "0.4.29", features = ["kv"] }
golem-rust = { version = "2.0.0-rc1", features = ["export_golem_agentic", "chrono"] }
golem-ai-llm = { git = "https://github.com/golemcloud/golem-ai", tag = "v0.5.0" }
golem-ai-llm-openrouter = { git = "https://github.com/golemcloud/golem-ai", tag = "v0.5.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wstd = { version = "=0.6.5", features = ["default", "json"] }
chrono = "0.4.42"
email_address = "0.2.9"
uuid = { version = "1.18.1", features = ["v4"] }
schemars = { version = "1.1.0", features = ["preserve_order"] }
regex = "1.12.2"
futures = "0.3.31"
